server:
  port: 8082

spring:
  application:
    name: job-crawler
  datasource:
    url: jdbc:mysql://localhost:3306/job_crawler
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  elasticsearch:
    uris: http://localhost:9200

crawler:
  thread-count: 5
  resume-based:
    max-page: 20
    min-salary: 8000
    max-salary: 30000
  sources:
    - name: linkedin
      base-url: https://www.linkedin.com/jobs
      list-url: https://www.linkedin.com/jobs/search
      use-selenium: true
      selectors:
        listItem: .job-card-container
        nextPage: .pagination__next-button
        title: .job-details-jobs-unified-top-card__job-title
        company: .job-details-jobs-unified-top-card__company-name
        location: .job-details-jobs-unified-top-card__bullet
        description: .job-details-jobs-unified-top-card__job-description
        skills: .job-details-jobs-unified-top-card__skills-section
        salary: .job-details-jobs-unified-top-card__salary-info
    - name: zhipin
      base-url: https://www.zhipin.com
      list-url: https://www.zhipin.com/web/geek/jobs?query=Java&city=101020100
      use-selenium: true
      selectors:
        listItem: .job-card-wrapper
        nextPage: .options-pages .next
        title: .job-title
        company: .company-name
        location: .job-location
        description: .job-description
        skills: .job-tags
        salary: .salary

# DashScope API密钥配置
dashscope:
  api:
    key: ${DASHSCOPE_API_KEY:sk-1fab8905c4a442da9e80c7ef81010a59}

logging:
  level:
    com.resumerecommendation: DEBUG