server:
  port: 8082

spring:
  application:
    name: job-crawler
  datasource:
    url: jdbc:mysql://localhost:3306/job_crawler
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  elasticsearch:
    uris: http://localhost:9200

crawler:
  thread-count: 5
  resume-based:
    max-parallel-crawlers: 5
    relevance-threshold: 0.7
    max-results-per-source: 100
    weights:
      skill: 0.4
      industry: 0.3
      experience: 0.3
  sources:
    - name: linkedin
      base-url: https://www.linkedin.com/jobs
      list-url: https://www.linkedin.com/jobs/search
      use-selenium: true
      selectors:
        listItem: .job-card-container
        nextPage: .pagination__next-button
        title: .job-details-jobs-unified-top-card__job-title
        company: .job-details-jobs-unified-top-card__company-name
        location: .job-details-jobs-unified-top-card__bullet
        description: .job-details-jobs-unified-top-card__job-description
        skills: .job-details-jobs-unified-top-card__skills-section
        salary: .job-details-jobs-unified-top-card__salary-info
    - name: zhipin
      base-url: https://www.zhipin.com
      list-url: https://www.zhipin.com/web/geek/job
      use-selenium: true
      selectors:
        listItem: .job-card-wrapper
        nextPage: .options-pages .next
        title: .job-title
        company: .company-name
        location: .job-location
        description: .job-description
        skills: .job-tags
        salary: .salary

logging:
  level:
    com.resumerecommendation: DEBUG 