server:
  port: 8083

spring:
  application:
    name: matching-service
  datasource:
    url: jdbc:mysql://localhost:3306/resume_recommendation?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  elasticsearch:
    uris: http://localhost:9200

openai:
  api:
    key: your-api-key-here

logging:
  level:
    com.resumerecommendation: DEBUG 