server:
  port: 8083

spring:
  application:
    name: resume-analysis-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # OpenAPI配置
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: method
      tags-sorter: alpha

# 通义千问 DashScope API 配置
dashscope:
  api:
    key: ${DASHSCOPE_API_KEY:sk-1fab8905c4a442da9e80c7ef81010a59}

logging:
  level:
    com.resumerecommendation: debug